### ISSUE TITLE
EPIC: Predatory loans

### ISSUE THREAD

**Issue by Dylan-Riley** [jleeboyd/family-bank-app#61]
### User Story
As a USER I want to be able to give the accounts "loans" which require a reoccurring payment, have interest, and have the capacity to be intentionally ruthless to create a teaching moment.

### Context / Additional Information
Long-term extra feature idea, should be split into many smaller user stories as work begins on this arm of the app.

### Acceptance Criteria
- [ ] Able to give and keep track of "loans" on accounts
- [ ] Loans should have their own activity to get an overview
- [ ] Should be sufficiently scary in design and implementation
