### ISSUE TITLE
EPIC: Debt

### ISSUE THREAD

**Issue by Dylan-Riley** [jleeboyd/family-bank-app#62]
### User Story
As a USER I want the accounts to be able to go negative and start accruing fees commonly associated with low or negative account balances.

### Context / Additional Information
Long-term extra feature idea, should be broken down into smaller user stories as work begins on this arm of the app

### Acceptance Criteria
- [ ] Accounts are able to go into debt
- [ ] Low/Negative automatic reoccurring fees
- [ ] Once again, needs to be scary in design and implementation
